### ISSUE TITLE
Not able to run the jar in Linux 

### ISSUE THREAD

**Issue by vinayagasundar** [yapplications/ADB-GUI#2]
It's only for Windows & Mac or it'll support linux also.

**Comment by shriharshs** [comment]
Trying to install it on Linux, but it ends up with error

(java:20738): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
02-01 12:36:17.074 Find adb on: linux
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at application.Main.findADBPath(Main.java:91)
	at application.Main.start(Main.java:38)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	... 1 more
Exception running application application.Main

**Comment by evgeni-shafran** [comment]
@vinayagasundar thanks for letting me know!
@shriharshs thanks for the stacktrace.

The app should work on linux but because i am not testing it on linux it can have its problems as you just encountered...

I think i solved the issue and uploaded a new binary (not tested it.. i dont have a linux machine): https://github.com/yapplications/ADB-GUI/releases/download/0.1.9v/ADB-GUI-Tool-0.1.9.zip

Please let me know if it works.

Also if you have any problems please refer to (just wrote it): https://github.com/yapplications/ADB-GUI/blob/master/README.md#submit-an-issue

And send me the logs so i can solve the problem.

Thanks again! and please let me know if it works :)

**Comment by vinayagasundar** [comment]
@evgeni-shafran Hi I've tested the latest version now I'm able to run the linux and Thanks for the immediate fix :+1:

**Comment by eddy-geek** [comment]
On Fedora 33 I had to first `dnf install openjfx-11.0.9.2`

and then I could launch with
```sh
cd .../ADB-GUI-Tool-0.1.9/ ; java --module-path /usr/lib/jvm/openjfx/ --add-modules javafx.controls,javafx.fxml -jar ADB-GUI-Tool-0.1.9.jar
```
(working directory is important as the app creates `appData/` in it)
