### ISSUE TITLE
Not working in many versions java on linux

### ISSUE THREAD

**Issue by phobro** [yapplications/ADB-GUI#4]
Tested jre\jdk 6\7 and 8v. 
Have you tested the application on Linux?

On 6 and 7 debug log:
```

Exception in thread "main" java.lang.UnsupportedClassVersionError: application/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

```

****
On 8 : 
```
java -jar ADB-GUI-Tool-0.1.9/ADB-GUI-Tool-0.1.9.jar 
Error: Could not find or load main class application.Main
```

What version of java is needed, why forever with this java troubles?

**Comment by phobro** [comment]
Also 
It would be great if you provided build instructions for app.

Because In java it's not obvious how make.

**Comment by plateaukao** [comment]
Hi, @phobro 
I think this project is built by IntelliJ IDEA.
So you can launch IntelliJ IDEA and open the project folder as an IntelliJ project.
I successfully built it on my Mac.
![image](https://user-images.githubusercontent.com/4084738/41188291-bc3a22d0-6bed-11e8-806a-9eae4161515c.png)

**Comment by zella** [comment]
Hi, I just adopted my fork to sbt. See build instruction(or download binary) here https://github.com/zella/ADB-GUI  Worked on linux
