### ISSUE TITLE
Minimal java version

### ISSUE THREAD

**Issue by ozon85** [yapplications/ADB-GUI#9]
Hello.
I can't run on java version "1.6.0_14":
"C:\Program Files\AV\jre\bin\java.exe" -jar e:\ADB-GUI-Tool-0.1.9\ADB-GUI-Tool-0.1.9.jar

Exception in thread "main" java.lang.UnsupportedClassVersionError: application/M
ain : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClassInternal(Unknown Source)
Could not find the main class: application.Main. Program will exit.

Pls, define minimal version of java in README

**Comment by My1** [comment]
Java 1.6 from what era was that? 
apparently the Maximum is Java 8 tho as #6 shows.
